package org.npd21tech.enums;

public enum PromotionTypeId {
    BOOK,
    MAGAZINE_AND_NEWSPAPER,
    STATIONERY_AND_OFFICE_SUPPLY,
    E_BOOKS_AND_AUDIOBOOKS,
    GIFT_ITEMS_AND_MERCHINDISE,
    BOARD_GAMES_AND_PUZZZLES,
    SCHOOL_AND_EDUCATIONAL_SUPPLIES,
    ART_AND_CRAFT_SUPPLIES,
    WRITING_INSTRUMENTS,
    BOOKSMARKS_AND_BOOK_ACCESSORIES,
    CALENDARS_PLANNERS,
    NOTEBOOKS_JOURNALS,
    TOYS_AND_COLLECTIBLES,
    MUSIC_AND_CDS,
    POSTERS_AND_PRINTS
}
